library(tRNAscanImport)

context("tRNA structure seqs")
test_that("tRNA structure seqs:",{
  file <- system.file("extdata", 
                      file = "sacCer3-tRNAs.ss.sort", 
                      package = "tRNAscanImport")
  tRNA <- tRNAscanImport::import.tRNAscanAsGRanges(file)
  tRNA <- tRNA[1]
  strList <- gettRNABasePairing(tRNA)
  actual <- tRNAscanImport:::.getAcceptorStem(tRNA, strList)
  expect_named(actual, c("prime5","prime3"))
  expect_named(actual[[1]], c("start","end"))
  expect_named(actual[[2]], c("start","end"))
  expect_equal(actual[[2]], list(start = 65,end = 71))
  actual <- tRNAscanImport:::.getDiscriminator(tRNA, strList)
  expect_equal(actual, 72)
  actual <- tRNAscanImport:::.getDstem(tRNA, strList)
  expect_named(actual, c("prime5","prime3"))
  expect_named(actual[[1]], c("start","end"))
  expect_named(actual[[2]], c("start","end"))
  expect_equal(actual[[2]], list(start = 21,end = 25))
  actual <- tRNAscanImport:::.getAnticodonStem(tRNA, strList)
  expect_named(actual, c("prime5","prime3"))
  expect_named(actual[[1]], c("start","end"))
  expect_named(actual[[2]], c("start","end"))
  expect_equal(actual[[2]], list(start = 38,end = 42))
  actual <- tRNAscanImport:::.getTstem(tRNA, strList)
  expect_named(actual, c("prime5","prime3"))
  expect_named(actual[[1]], c("start","end"))
  expect_named(actual[[2]], c("start","end"))
  expect_equal(actual[[2]], list(start = 60,end = 64))
  actual <- tRNAscanImport:::.getDloop(tRNA, strList)
  expect_named(actual, c("start","end"))
  expect_equal(actual, list(start = 14,end = 20))
  actual <- tRNAscanImport:::.getAnticodonloop(tRNA, strList)
  expect_named(actual, c("start","end"))
  expect_equal(actual, list(start = 31,end = 37))
  actual <- tRNAscanImport:::.getVariableLoop(tRNA, strList)
  expect_named(actual, c("start","end"))
  expect_equal(actual, list(start = 43,end = 47))
  actual <- tRNAscanImport:::.getTloop(tRNA, strList)
  expect_named(actual, c("start","end"))
  expect_equal(actual, list(start = 53,end = 59))
  # check that the sequences are unharmed by chopping it into pieces
  tRNA <- tRNAscanImport::import.tRNAscanAsGRanges(file)
  seqs <- tRNAscanImport::gettRNAstructureSeqs(tRNA,
                                               joinCompletely = TRUE,
                                               joinFeatures = FALSE)
  seqsChars <- gsub("-","",as.character(seqs))
  expect_equal(seqsChars,as.character(tRNA$tRNA_seq))
  expect_named(S4Vectors::metadata(seqs),"tRNA_structures")
})